### ISSUE TITLE
As a EDP User, I want to have capability to deploy Sonar as a part of add-ons approach

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#35]
Use Upstream helm chart deploy sonar as a shared component

- Use the Upstream Sonar helm chart;
- Use the Latest LTS version;
- Use Add-ons approach (put the result in [add-ons repo](https://github.com/epam/edp-cluster-add-ons));
- Integrate EDP instances with External Sonar;
- Ensure EDP can be deployed without Sonar-Operator;

**Comment by alezander86** [comment]
From now on there is an opportunity to install and use the latest upstream SonarQube  LTS version using our [add-ons Helm chart approach](https://github.com/epam/edp-cluster-add-ons). This provides a simple and convenient way to integrate SonarQube both during a clean installation of EDP and when connecting to an existing installed version of EDP.

By using the add-ons Helm chart approach, we can easily and seamlessly deploy the SonarQube LTS along with EDP. Alternatively, if you already have an installed version of EDP, you can install the SonarQube add-ons Helm chart and connect it instead of the [edp-sonar-operator](https://github.com/epam/edp-sonar-operator). For more detailed integration information, you can refer to the article on our [EDP website](https://epam.github.io/edp-install/operator-guide/sonarqube/?h=sonar).
