### ISSUE TITLE
As a EDP User, I want to have capability to deploy Nexus as a part of add-ons approach

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#36]
Use Upstream helm chart deploy Nexus as a shared component

- Use the Upstream Nexus helm chart;
- Use the Latest LTS version;
- Use Add-ons approach (put the result in [add-ons repo](https://github.com/epam/edp-cluster-add-ons));
- Integrate EDP instances with External Nexus;
- Ensure EDP can be deployed without Nexus-Operator;

**Comment by alezander86** [comment]
From now on there is an opportunity to install and use the latest upstream Sonatype Nexus Repository LTS version using our [add-ons Helm chart approach](https://github.com/epam/edp-cluster-add-ons). This provides a simple and convenient way to integrate Sonatype Nexus Repository both during a clean installation of EDP and when connecting to an existing installed version of EDP.

By using the add-ons Helm chart approach, we can easily and seamlessly deploy the Sonatype Nexus Repository LTS along with EDP. Alternatively, if you already have an installed version of EDP, you can install the Sonatype Nexus Repository add-ons Helm chart and connect it instead of the [edp-nexus-operator](https://github.com/epam/edp-nexus-operator).
